name: gen
version: 0.0.1
homepage: none
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"
description: A new Flutter package project.
dependencies:
  envied: "^0.3.0+3"
  equatable: "^2.0.5"
  flutter:
    sdk: flutter
  flutter_svg: "^2.0.7"
  json_annotation: "^4.8.1"
  lottie: "^2.6.0"
  vexana: "^3.5.4"
dev_dependencies:
  build_runner: "^2.4.6"
  envied_generator: "^0.3.0+3"
  flutter_gen_runner: "^5.3.2"
  flutter_test:
    sdk: flutter
  json_serializable: "^6.7.1"
  pubspec_dependency_sorter: "^1.0.5"
  very_good_analysis: "^5.1.0"
flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml
flutter:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/
