name: "health_app"
version: "1.0.0+1"
publish_to: none
environment:
  sdk: "^3.5.3"
description: A new Flutter project.
dependencies:
  auto_route: "^7.8.4"
  common:
    path: module/common
  core:
    path: module/core
  cupertino_icons: "^1.0.2"
  easy_localization: "^3.0.3"
  easy_logger: "^0.0.2"
  equatable: "^2.0.5"
  flutter:
    sdk: flutter
  flutter_bloc: "^8.1.3"
  gen:
    path: module/gen
  get_it: "^7.6.4"
  google_fonts: "^6.1.0"
  kartal: "^3.5.0"
  logger: "^2.0.2+1"
  vexana: "^3.5.4"
  widgets:
    path: module/widgets
dev_dependencies:
  auto_route_generator: "^7.3.2"
  bloc_test: "^9.1.5"
  build_runner: "^2.4.6"
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: "^2.0.0"
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: "^5.3.2"
  pubspec_dependency_sorter: "^1.0.5"
  very_good_analysis: "^5.1.0"
flutter_Launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - asset/translation/
